### ISSUE TITLE
Only newly ingested sequences showing on CovSpectrum

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#1125]
I've noticed that currently there are only a total of 4k sequences on covspectrum. As if only the most recently(=newly available) sequences made it into the dataset and all the old ones were lost. Maybe incremental ingest gone wrong? Or maybe GISAID sent a buggy dump with only the latest data?

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?&

Might be worth adding a metric on the total number of sequences and have grafana alert when it's decreasing to spot this automatically in the future 🤓

**Comment by chaoran-chen** [comment]
Thank you very much for notifying us, @corneliusroemer! Indeed, something went wrong when ingesting GISAID data this morning and it's possible that only the newly available data were loaded, I'll check.

For now, I fixed it by loading the previous dataset.

Good idea to install an alert if the number of sequences decreases! I'll create a ticket in our (internal) servers repository!

**Comment by corneliusroemer** [comment]
Bug is back:

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?&

<img width="1566" height="714" alt="Image" src="https://github.com/user-attachments/assets/5f5fb334-c8d5-430b-a6a2-f2d0815bb40f" />

Only 5k sequences now

**Comment by FedeGueli** [comment]
Thx @corneliusroemer ! it obviously affects everything then also growth advantages
